"""update_payroll_approval_model

Revision ID: 0f4da6862744
Revises: 3103dbcea365
Create Date: 2025-10-13 13:15:05.225373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f4da6862744'
down_revision = '3103dbcea365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_approval', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period_year', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('period_month', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('employee_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('admin_approved_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('finance_processed_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rejected_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('admin_approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('finance_processed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('rejected_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.Text(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['finance_processed_by'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['admin_approved_by'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['rejected_by'], ['id'])
        batch_op.drop_column('finance_reviewed_at')
        batch_op.drop_column('payroll_period')
        batch_op.drop_column('staff_count')
        batch_op.drop_column('admin_reviewed_at')
        batch_op.drop_column('admin_comments')
        batch_op.drop_column('admin_reviewer')
        batch_op.drop_column('finance_reviewer')
        batch_op.drop_column('finance_comments')

    with op.batch_alter_table('staff_payroll', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['approved_by_admin'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['approved_by_finance'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_payroll', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('payroll_approval', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finance_comments', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('finance_reviewer', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('admin_reviewer', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('admin_comments', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('admin_reviewed_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('staff_count', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('payroll_period', sa.VARCHAR(length=32), nullable=False))
        batch_op.add_column(sa.Column('finance_reviewed_at', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['admin_reviewer'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['finance_reviewer'], ['id'])
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('rejected_at')
        batch_op.drop_column('finance_processed_at')
        batch_op.drop_column('admin_approved_at')
        batch_op.drop_column('rejected_by')
        batch_op.drop_column('finance_processed_by')
        batch_op.drop_column('admin_approved_by')
        batch_op.drop_column('employee_count')
        batch_op.drop_column('period_month')
        batch_op.drop_column('period_year')

    # ### end Alembic commands ###
