"""Initial migration for all models

Revision ID: 259b04676887
Revises: 87f120f83e37
Create Date: 2025-09-16 09:49:48.364194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '259b04676887'
down_revision = '87f120f83e37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=200), nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('verification_code', sa.VARCHAR(length=6), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
