"""add_comprehensive_employee_salary_fields

Revision ID: 3103dbcea365
Revises: 6b60d92741a1
Create Date: 2025-10-13 12:46:59.470400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3103dbcea365'
down_revision = '6b60d92741a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('basic_salary', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('housing_allowance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('transport_allowance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('medical_allowance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('special_allowance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('overtime_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tax_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pension_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('bank_account_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bank_sort_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('employment_type', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('grade_level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('step', sa.Integer(), nullable=True))

    # Note: Foreign key constraints for staff_payroll approval workflow
    # will be handled in a separate migration if needed
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('step')
        batch_op.drop_column('grade_level')
        batch_op.drop_column('employment_type')
        batch_op.drop_column('bank_sort_code')
        batch_op.drop_column('bank_account_number')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('pension_number')
        batch_op.drop_column('tax_number')
        batch_op.drop_column('overtime_rate')
        batch_op.drop_column('special_allowance')
        batch_op.drop_column('medical_allowance')
        batch_op.drop_column('transport_allowance')
        batch_op.drop_column('housing_allowance')
        batch_op.drop_column('basic_salary')

    # ### end Alembic commands ###
