"""Add staff_code to Employee

Revision ID: 4b55039128b6
Revises: 952140613a47
Create Date: 2025-10-11 18:47:23.489398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b55039128b6'
down_revision = '952140613a47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_code', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_employee_staff_code'), ['staff_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_staff_code'))
        batch_op.drop_column('staff_code')

    # ### end Alembic commands ###
