"""add salary components to staff payroll

Revision ID: 5ff3ac771169
Revises: add_payroll_docs_fields
Create Date: 2025-11-20 23:54:36.630701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ff3ac771169'
down_revision = 'add_payroll_docs_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Skipping budgets table modification due to SQLite limitation with default values
    
    with op.batch_alter_table('staff_payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('basic_salary', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('housing_allowance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('transport_allowance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('meal_allowance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('other_allowances', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_payroll', schema=None) as batch_op:
        batch_op.drop_column('other_allowances')
        batch_op.drop_column('meal_allowance')
        batch_op.drop_column('transport_allowance')
        batch_op.drop_column('housing_allowance')
        batch_op.drop_column('basic_salary')

    # Skipping budgets table rollback
    # ### end Alembic commands ###
