"""Add deduction management and payroll approval workflow

Revision ID: 6b60d92741a1
Revises: c22ca86816c5
Create Date: 2025-10-13 09:51:44.664524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b60d92741a1'
down_revision = 'c22ca86816c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_approval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_period', sa.String(length=32), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('staff_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=False),
    sa.Column('admin_reviewer', sa.Integer(), nullable=True),
    sa.Column('finance_reviewer', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('admin_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('finance_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('admin_comments', sa.Text(), nullable=True),
    sa.Column('finance_comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['admin_reviewer'], ['user.id'], ),
    sa.ForeignKeyConstraint(['finance_reviewer'], ['user.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_deduction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('deduction_type', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff_payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_status', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('approved_by_admin', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_by_finance', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('submitted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('admin_approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('finance_approved_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_staff_payroll_approved_by_finance', 'user', ['approved_by_finance'], ['id'])
        batch_op.create_foreign_key('fk_staff_payroll_approved_by_admin', 'user', ['approved_by_admin'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_payroll', schema=None) as batch_op:
        batch_op.drop_constraint('fk_staff_payroll_approved_by_finance', type_='foreignkey')
        batch_op.drop_constraint('fk_staff_payroll_approved_by_admin', type_='foreignkey')
        batch_op.drop_column('finance_approved_at')
        batch_op.drop_column('admin_approved_at')
        batch_op.drop_column('submitted_at')
        batch_op.drop_column('approved_by_finance')
        batch_op.drop_column('approved_by_admin')
        batch_op.drop_column('approval_status')

    op.drop_table('staff_deduction')
    op.drop_table('payroll_approval')
    # ### end Alembic commands ###
