"""Add new employee fields

Revision ID: 8497cde072f3
Revises: ad15897a9137
Create Date: 2025-09-22 16:32:19.885794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8497cde072f3'
down_revision = 'ad15897a9137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_payroll', sa.Float(), nullable=False),
    sa.Column('total_deductions', sa.Float(), nullable=True),
    sa.Column('generated_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_salary_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_history_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('salary', sa.Float(), nullable=False),
    sa.Column('deduction', sa.Float(), nullable=True),
    sa.Column('net_pay', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['payroll_history_id'], ['payroll_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payroll_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_history_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['payroll_history_id'], ['payroll_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('permanent_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('degree', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('institution', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('current_certification', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('present_assignment', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('employment_dates', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('past_job_title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('past_employer_dates', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('past_accomplishments', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('technical_skills', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('soft_skills', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('certifications', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('team_info', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sectional_head_upgrade', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('job_description_upgrade', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('job_description_upgrade')
        batch_op.drop_column('sectional_head_upgrade')
        batch_op.drop_column('notes')
        batch_op.drop_column('team_info')
        batch_op.drop_column('certifications')
        batch_op.drop_column('soft_skills')
        batch_op.drop_column('technical_skills')
        batch_op.drop_column('past_accomplishments')
        batch_op.drop_column('past_employer_dates')
        batch_op.drop_column('past_job_title')
        batch_op.drop_column('employment_dates')
        batch_op.drop_column('present_assignment')
        batch_op.drop_column('current_certification')
        batch_op.drop_column('institution')
        batch_op.drop_column('degree')
        batch_op.drop_column('phone')
        batch_op.drop_column('permanent_address')
        batch_op.drop_column('current_address')

    op.drop_table('payroll_transactions')
    op.drop_table('employee_salary_history')
    op.drop_table('payroll_history')
    # ### end Alembic commands ###
