"""Add StaffPayroll table

Revision ID: 952140613a47
Revises: 822a6bc34171
Create Date: 2025-10-11 18:15:59.955661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '952140613a47'
down_revision = '822a6bc34171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_payroll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=True),
    sa.Column('period_month', sa.Integer(), nullable=True),
    sa.Column('site', sa.String(length=128), nullable=True),
    sa.Column('employment_date', sa.Date(), nullable=True),
    sa.Column('bank_name', sa.String(length=128), nullable=True),
    sa.Column('account_number', sa.String(length=64), nullable=True),
    sa.Column('designation', sa.String(length=128), nullable=True),
    sa.Column('work_days', sa.Integer(), nullable=True),
    sa.Column('days_worked', sa.Integer(), nullable=True),
    sa.Column('overtime_hours', sa.Float(), nullable=True),
    sa.Column('gross', sa.Float(), nullable=True),
    sa.Column('arrears', sa.Float(), nullable=True),
    sa.Column('rice_contribution', sa.Float(), nullable=True),
    sa.Column('loan_or_salary_advance', sa.Float(), nullable=True),
    sa.Column('jaco', sa.Float(), nullable=True),
    sa.Column('minna_paye', sa.Float(), nullable=True),
    sa.Column('late_deduction', sa.Float(), nullable=True),
    sa.Column('balance_salary', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff_payroll')
    # ### end Alembic commands ###
