"""Upgrade Employee model for full biodata and promotion fields

Revision ID: ad15897a9137
Revises: e533e40d1646
Create Date: 2025-09-22 04:35:40.659036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad15897a9137'
down_revision = 'e533e40d1646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('next_of_kin', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('next_of_kin_relationship', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('next_of_kin_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('next_of_kin_phone', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('position', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('date_of_employment', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('employment_letter', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('sectional_head', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('job_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('academic_qualification_at_employment', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('present_academic_qualification', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('present_academic_qualification')
        batch_op.drop_column('academic_qualification_at_employment')
        batch_op.drop_column('job_description')
        batch_op.drop_column('sectional_head')
        batch_op.drop_column('employment_letter')
        batch_op.drop_column('date_of_employment')
        batch_op.drop_column('position')
        batch_op.drop_column('next_of_kin_phone')
        batch_op.drop_column('next_of_kin_address')
        batch_op.drop_column('next_of_kin_relationship')
        batch_op.drop_column('next_of_kin')
        batch_op.drop_column('dob')

    # ### end Alembic commands ###
