"""ensure employee_id field in uploaded_file table

Revision ID: c22ca86816c5
Revises: eff9e6c0443f
Create Date: 2025-10-13 01:04:59.523549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c22ca86816c5'
down_revision = 'eff9e6c0443f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_uploaded_file_employee_id', 'employee', ['employee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_file', schema=None) as batch_op:
        batch_op.drop_constraint('fk_uploaded_file_employee_id', type_='foreignkey')
        batch_op.drop_column('employee_id')

    # ### end Alembic commands ###
