"""remove unique constraint from employee email field

Revision ID: eff9e6c0443f
Revises: 4b55039128b6
Create Date: 2025-10-12 07:51:30.984105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eff9e6c0443f'
down_revision = '4b55039128b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_file', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.create_foreign_key('fk_uploaded_file_uploaded_by', 'user', ['uploaded_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_file', schema=None) as batch_op:
        batch_op.drop_constraint('fk_uploaded_file_uploaded_by', type_='foreignkey')
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
